### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by zednak12** [expresstechsoftware/connect-learndash-discord-addon#80]
Hello, when the user's access to learndash training ends, the discord role is taken. In addition to this, I want to disconnect the user from discord. How can I edit?

**Comment by younes-dro** [comment]
Hi @zednak12 
You can go to : Users-> All users.
Find the user.
Under the column : LD Discord Connection  and click the button  : disconnect from discrod.
You can force disconnect the student from discord :

![disconnect1](https://user-images.githubusercontent.com/31171/218656503-721d290a-2f16-4fda-ab5b-79fd2c5da4ce.png)

**Comment by zednak12** [comment]
I want to do it automatically, not manually when the course access ends

**Comment by younes-dro** [comment]
@zednak12 
did you enable the settings option :  Advanved -> Remove student discord role when course access expires?  option
![remove-student-discord-role](https://user-images.githubusercontent.com/31171/219034502-d4e83531-6684-464a-bbcb-04f97352c23e.png)

Can you please do a check and give me a feedback

**Comment by zednak12** [comment]
Hello again. This command causes the user to remove their role on the server, but the person remains on the server. I want him to both remove his role and disconnect from the server.

**Comment by younes-dro** [comment]
Yes @zednak12 
This is the default behavior of the plugin and meets the majority of user needs.
In future versions, we will take into consideration if most users of our plugins need it.

We can discuss if you need a specific version for your requirements with @ravisoni6262
